### ISSUE TITLE
DB_ORM and JOIN

### ISSUE THREAD

**Issue by nyunyu95** [spadefoot/kohana-orm-leap#20]
Hello, 

I'm trying to make some join statements with DB_ORM. However, anything seems to work I'm always getting such errors:

"Kohana_InvalidProperty_Exception [ 0 ]: Message: Unable to set the specified property. Reason: Property [...] is either inaccessible or undefined."

We can read on http://orm.spadefootcode.com/tutorials/building-sql-statements/#read :
"Both DB_SQL and DB_ORM can join tables. However, DB_ORM cannot return data from such tables."

Does it mean that we only can make join statements with the DB_SQL ?

**Comment by spadefoot** [comment]
Would you paste an example of what you are trying to accomplish?

In general, a result set generated by DB_ORM will only return models of the specified type; therefore, since a model essentially represents a row in a database table, an instance of a model class will not store any data from the joined tables...for that you will need to use DB_SQL.  I will look into updating the Web site's documentation to help clarify this distinction.

**Comment by nyunyu95** [comment]
Thanks for your precisions. That's fine for me ! :)
