### ISSUE TITLE
Column and table name wrapping for Oracle

### ISSUE THREAD

**Issue by mazu0** [spadefoot/kohana-orm-leap#88]
Hi,

When trying to use DB_ORM::select for oracle (config: 'type' => 'SQL', 'dialect' => 'Oracle', 'driver' => 'Standard') the builder wraps all the column names and the table name in quotes which leads to unsuccessful execution. The wrapping is done in file leap\classes\Base\DB\Oracle\Precompiler.php , function prepare_identifier line 97.

If i comment the lines from 95 to 99 the queries are built and executed normally.

BTW: you rock and rule my good sir :)

Thanks for the good work and have a good day, MzZz

**Comment by bluesnowman** [comment]
See section 8 on this page (http://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements008.htm) regarding quoting identifiers in Oracle.  Essentially, Oracle treats non-quoted identifiers as being uppercase.  So the following will be true:

```
roles
ROLES
"ROLES"
```

These are therefore all the same.  Since leap quotes its identifiers, I would bet that if you wrote the table or column name in all uppercase letters your queries would work.

**Comment by mazu0** [comment]
@bluesnowman: it worked, thank you very much for your help
